### ISSUE TITLE
accelerate BWA-MEM

### ISSUE THREAD

**Issue by lyd0527** [nahmedraja/GASAL2#3]
Hi,

I am looking for progrom for `BWA-MEM` and `Minimap2`. But I am new about `GPU`. Could u pls give us some simple examples for accelerating `BWA-MEM`?  Besides, can `GASAL2` be used for `minimap2` acceleration? Thank you very much!

Best,

Yuanda

**Comment by nahmedraja** [comment]
gase-gasal2 (https://github.com/nahmedraja/gase-gasal2) is the GPU acceleration of BWA-MEM. GASE aligner (https://github.com/nahmedraja/GASE) is an extension of BWA-MEM and gives exactly the same result if executed with "-r" option. Hence, `./gase aln -r  ... ` is equivalent to `./bwa mem ...`

GASAL2 in its current form is suitable for Illumina reads.
